"""Cue Cards — a launch-time feature tour for gBuilder.

A simple card deck: each card shows a real screenshot of the feature (curated portions of
the actual UI, generated by scripts/gen_cue_shots.py into assets/cue/<kind>.png), a title,
and a short explanation. Navigate with the ‹ / › arrows or the keyboard. "Don't show at
launch" + the Settings Help tab control whether it auto-opens; reopen from Help → Feature
Tour.
"""
from __future__ import annotations

import re
from pathlib import Path

from PySide6.QtCore import QRectF, Qt
from PySide6.QtGui import QColor, QFont, QPainter, QPixmap
from PySide6.QtWidgets import (
    QCheckBox, QDialog, QHBoxLayout, QLabel, QPushButton, QVBoxLayout, QWidget,
)

_CUE_DIR = Path(__file__).resolve().parent / "assets" / "cue"


def _theme_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", (name or "dark").lower()) or "dark"


def _cue_candidates(cue_dir: Path, slug: str, dark: bool, kind: str) -> list[Path]:
    """Screenshot search order: the running theme's own shots first, then its
    light/dark *family* (so Sand/Blue/Green reuse the Light set), then dark, then
    a legacy flat file."""
    family = "dark" if dark else "light"
    return [cue_dir / slug / f"{kind}.png",
            cue_dir / family / f"{kind}.png",
            cue_dir / "dark" / f"{kind}.png",
            cue_dir / f"{kind}.png"]


# Each card: art kind (-> assets/cue/<kind>.png), title, body. Order = tour order.
FEATURE_CARDS = [
    ("welcome", "Welcome to gBuilder",
     "Design real networks and cloud systems by drawing them, then run them as live Docker "
     "containers. Take the tour with the ‹ / › arrows (or your keyboard)."),
    ("canvas", "Build by drawing",
     "Drag elements from the palette onto the canvas and connect them with a right-drag. The "
     "diagram you draw is the system — GINI compiles it into a real runtime when you Run."),
    ("wizard", "X-ray & the AI Wizard",
     "Unsure what connects to what? Long-press an element to see its valid neighbours as "
     "ghosts, or state a goal and the Wizard walks you through building it, one tap at a time."),
    ("run", "Run on real Docker",
     "Press Run and your topology launches as real containers — a C router, switches, "
     "Kubernetes, databases and more. Badges turn green; double-click an element to log in."),
    ("cost", "The GINI $ cost meter",
     "A live 'cloud bill' ticks up while the lab runs, split by category, so pay-as-you-go is "
     "tangible. Edit the per-hour rates under Settings → Pricing."),
    ("metrics", "Live metrics",
     "Select a running element and open the Live tab to watch its CPU, memory, throughput and "
     "latency in real time — the same telemetry that feeds the dashboard."),
    ("cloud", "Cloud services & VPCs",
     "Drop managed services — databases, caches, queues, object storage — as real containers, "
     "and group them in a VPC box. Each VPC becomes its own isolated network."),
    ("serverless", "Serverless functions",
     "Add a Function and write a Python handler in the inspector. Invoke it there to see the "
     "response, and Deploy code changes without restarting the rest of the lab."),
    ("router", "Program the router",
     "Open the Router Lab on any router to build its packet-processing pipeline and run real "
     "CLI commands against the live gRouter."),
    ("ai", "Ask GINI",
     "Ask in plain English. GINI builds, explains warnings, traces packet paths and guides you "
     "with the Wizard — and it still helps even with no local LLM connected."),
    ("settings", "Make it yours",
     "Settings (Ctrl+,) is organized into tabs — Appearance, Networking, GINI AI, Naming and "
     "Pricing. Reopen this tour any time from Help → Feature Tour."),
]


def _qcolor(spec) -> QColor:
    if isinstance(spec, QColor):
        return spec
    if isinstance(spec, str) and spec.startswith("rgba("):
        n = [int(float(x)) for x in spec[5:-1].split(",")]
        return QColor(n[0], n[1], n[2], n[3] if len(n) > 3 else 255)
    return QColor(spec)


class CardArt(QWidget):
    """Shows the current card's screenshot, scaled to fit (keeping aspect), centered."""

    def __init__(self, theme) -> None:
        super().__init__()
        self.theme = theme
        self._pix: QPixmap | None = None
        self._kind = "welcome"
        self.setMinimumHeight(320)

    def set_kind(self, kind: str) -> None:
        self._kind = kind
        # prefer the screenshot for the running theme; fall back within the light/dark
        # family (so Sand/Blue/Green reuse the Light shots), then dark, then legacy flat
        slug = _theme_slug(self.theme.theme.name)
        pix = QPixmap()
        for cand in _cue_candidates(_CUE_DIR, slug, self.theme.theme.dark, kind):
            if cand.exists():
                pix = QPixmap(str(cand))
                if not pix.isNull():
                    break
        self._pix = pix if not pix.isNull() else None
        self.update()

    def paintEvent(self, _e) -> None:
        t = self.theme.theme
        p = QPainter(self)
        p.setRenderHint(QPainter.SmoothPixmapTransform, True)
        p.setRenderHint(QPainter.Antialiasing, True)
        r = QRectF(self.rect())
        p.fillRect(r, _qcolor(getattr(t, "panel", t.bg)))
        if self._pix is not None and not self._pix.isNull():
            # fit the full-resolution pixmap into the available area keeping aspect, and let
            # the painter scale it straight to device pixels — pre-scaling to logical size
            # first would throw away resolution and blur on Retina/HiDPI displays.
            avail = r.adjusted(12, 12, -12, -12)
            pw, ph = self._pix.width(), self._pix.height()
            s = min(avail.width() / pw, avail.height() / ph)
            tw, th = pw * s, ph * s
            target = QRectF(r.center().x() - tw / 2, r.center().y() - th / 2, tw, th)
            p.drawPixmap(target, self._pix, QRectF(0, 0, pw, ph))
        else:                                          # graceful fallback if an image is missing
            p.setPen(_qcolor(getattr(t, "muted", t.text)))
            f = QFont(); f.setPointSize(13); p.setFont(f)
            p.drawText(r, Qt.AlignCenter, self._kind)
        p.end()


class CueCards(QDialog):
    """The card-deck dialog. `persist` is called after the user changes the launch pref."""

    def __init__(self, parent, theme, settings, cards=FEATURE_CARDS, persist=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("gBuilder — Feature Tour")
        self.setModal(True)
        self.setMinimumSize(760, 660)
        self.theme = theme
        self.settings = settings
        self._cards = list(cards)
        self._persist = persist or (lambda: None)
        self._i = 0

        t = theme.theme
        self.setStyleSheet(
            f"QDialog {{ background: {_color(t.bg)}; }}"
            f"QLabel {{ color: {_color(t.text)}; }}"
            f"QLabel#Body {{ color: {_color(getattr(t, 'muted', t.text))}; font-size: 15px; }}")

        lay = QVBoxLayout(self)
        lay.setContentsMargins(20, 20, 20, 16)
        lay.setSpacing(12)
        self.art = CardArt(theme)
        lay.addWidget(self.art, 1)
        self.title = QLabel()
        tf = QFont(); tf.setBold(True); tf.setPointSize(21)
        self.title.setFont(tf)
        lay.addWidget(self.title)
        self.body = QLabel(); self.body.setObjectName("Body"); self.body.setWordWrap(True)
        self.body.setMinimumHeight(74)
        lay.addWidget(self.body)

        footer = QHBoxLayout()
        self.dont = QCheckBox("Don't show at launch")
        self.dont.setChecked(not settings.show_help_on_launch)
        self.dont.toggled.connect(self._on_dont)
        footer.addWidget(self.dont)
        footer.addStretch(1)
        self.back = QPushButton("‹ Back"); self.back.clicked.connect(lambda: self._go(-1))
        self.count = QLabel(); self.count.setObjectName("Body")
        self.next = QPushButton("Next ›"); self.next.clicked.connect(lambda: self._go(1))
        done = QPushButton("Done"); done.setObjectName("Accent"); done.clicked.connect(self.accept)
        for w in (self.back, self.count, self.next, done):
            footer.addWidget(w)
        lay.addLayout(footer)

        self._show_card()

    # -- navigation --------------------------------------------------------- #
    def _go(self, delta: int) -> None:
        self._i = max(0, min(len(self._cards) - 1, self._i + delta))
        self._show_card()

    def _show_card(self) -> None:
        kind, title, body = self._cards[self._i]
        self.art.set_kind(kind)
        self.title.setText(title)
        self.body.setText(body)
        self.count.setText(f"{self._i + 1} / {len(self._cards)}")
        self.back.setEnabled(self._i > 0)
        self.next.setEnabled(self._i < len(self._cards) - 1)

    def keyPressEvent(self, e) -> None:
        if e.key() in (Qt.Key_Right, Qt.Key_Space):
            self._go(1)
        elif e.key() == Qt.Key_Left:
            self._go(-1)
        elif e.key() == Qt.Key_Escape:
            self.accept()
        else:
            super().keyPressEvent(e)

    # -- preference --------------------------------------------------------- #
    def _on_dont(self, checked: bool) -> None:
        self.settings.show_help_on_launch = not checked
        self._persist()


def _color(spec) -> str:
    return _qcolor(spec).name()
