"""Predicate explainer — the deterministic "why is this objective red?" fact.

The oracle doesn't just say met/unmet; it can report the *counterexample*: which atom of a structural
predicate is failing, in board terms ("no switch is wired to a router", "no path from a web app to a
database", "a cloud can still reach the database"). That fact is generated by walking the topology —
never by the model. The Reasoning persona then turns the fact into a warm, specific diagnosis; this is
what makes the multi-agent answers grounded in the student's actual board instead of canned.

Handles the structural predicates missions use (`exists`, `count`, `link`, `path`, `through`,
`contains_type`, and their `not`), including `and`/`or` compounds — reporting the atoms that are the
problem. Behavioral probes explain as "run it to check".
"""
from __future__ import annotations

import ast

from .devices import REGISTRY
from .objectives import TopologyWorld, _call, parse_check


def _label(type_key: str) -> str:
    spec = REGISTRY.get(type_key)
    return (getattr(spec, "label", None) or type_key).lower() if spec else type_key


def _atom_true(node: ast.Call, world) -> bool:
    args = [a.id if isinstance(a, ast.Name) else getattr(a, "value", None) for a in node.args]
    try:
        return bool(_call(node.func.id, args, world))
    except Exception:
        return False


def _describe(node: ast.Call, negated: bool) -> str:
    """A board-terms reason why this atom is the problem (given it violates the objective)."""
    fn = node.func.id
    a = [x.id if isinstance(x, ast.Name) else getattr(x, "value", "") for x in node.args]
    if fn == "exists":
        return (f"there's a {_label(a[0])} but there shouldn't be" if negated
                else f"there's no {_label(a[0])} on the board yet")
    if fn == "count":
        return f"you don't have enough {_label(a[0])}s yet"
    if fn == "link":
        return (f"a {_label(a[0])} is wired directly to a {_label(a[1])} and shouldn't be" if negated
                else f"no {_label(a[0])} is wired to a {_label(a[1])} yet")
    if fn == "path":
        return (f"a {_label(a[0])} can still reach a {_label(a[1])} (it should be isolated)" if negated
                else f"a {_label(a[0])} can't reach a {_label(a[1])} — they're not connected through")
    if fn == "through":
        return (f"traffic from a {_label(a[1])} to a {_label(a[2])} doesn't pass through the "
                f"{_label(a[0])} (or there's a path around it)")
    if fn == "contains_type":
        return (f"a {_label(a[1])} sits inside the {_label(a[0])} and shouldn't" if negated
                else f"no {_label(a[1])} is inside the {_label(a[0])} yet")
    return f"the condition {fn} isn't satisfied"


def _walk(node, world, negated: bool, out: list) -> None:
    if isinstance(node, ast.BoolOp):
        for v in node.values:                       # for and/or, report each failing branch
            _walk(v, world, negated, out)
    elif isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
        _walk(node.operand, world, not negated, out)
    elif isinstance(node, ast.Call):
        true = _atom_true(node, world)
        violates = true if negated else (not true)  # atom is the problem if it's the wrong way round
        if violates:
            r = _describe(node, negated)
            if r not in out:
                out.append(r)


def why_unmet(check: str, world) -> str:
    """A concrete, board-grounded reason an (unmet) structural objective is failing — or '' if it
    actually holds / can't be explained. Deterministic: the oracle reporting, not reasoning."""
    try:
        node = parse_check(check)
    except Exception:
        return ""
    out: list[str] = []
    _walk(node, world, False, out)
    return "; ".join(out)


def diagnose(objective, world) -> str:
    """The reason an objective is red (structural) or a prompt to run it (behavioral)."""
    if getattr(objective, "kind", "structural") == "behavioral":
        return "run it to check (this one needs the live system)"
    check = getattr(objective, "check", "")
    return why_unmet(check, world) if check else ""
