"""Launching with arguments: the argument IS the lesson for half these programs.

`sgrind 20` fits in the buffer cache and `sgrind 60` does not — that contrast is an entire round
of the observation guide. Before this, /run wrote `prog + " &"` and there was no way to pass the
number at all, so the guide asked for something the product could not do.

Two things can rot here:

  * the UI's _PROG_ARGS map drifts from what the C programs actually read from argv, and the
    argument box either offers a parameter the program ignores or hides one that matters;
  * the agent's argument sanitiser loosens, and /run — which writes into a real shell — becomes a
    command injection.

Both are checked against the real sources rather than a copy of them.
"""
import ast
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
LAB = ROOT / "frontend-ng" / "src" / "gini" / "ui" / "machine_lab.py"
AGENT = ROOT / "backend" / "xv6" / "gini_agent.py"
PATCH = ROOT / "backend" / "xv6" / "gini_patch.py"


def _prog_args() -> dict:
    """Read _PROG_ARGS out of machine_lab.py without importing Qt."""
    if not LAB.exists():
        pytest.skip("machine_lab.py not present")
    for node in ast.parse(LAB.read_text()).body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == "_PROG_ARGS":
            return {k.value: v.value for k, v in zip(node.value.keys, node.value.values)}
    pytest.fail("_PROG_ARGS not found")


def _uprog_bodies() -> dict:
    if not PATCH.exists():
        pytest.skip("gini_patch.py not present")
    s = PATCH.read_text()
    blk = s[s.index("_UPROGS = {"):s.index("\ndef add_uprog")]
    return dict(re.findall(r'^    "(\w+)": """(.*?)"""', blk, re.S | re.M))


def _safe_args():
    """Pull the sanitiser out of the agent without importing it (it opens a serial port)."""
    if not AGENT.exists():
        pytest.skip("gini_agent.py not present")
    fn = next(n for n in ast.parse(AGENT.read_text()).body
              if isinstance(n, ast.FunctionDef) and n.name == "_safe_args")
    ns: dict = {}
    exec(compile(ast.Module(body=[fn], type_ignores=[]), "<agent>", "exec"), ns)
    return ns["_safe_args"]


# -- the map matches the C ------------------------------------------------- #

def test_every_program_offered_an_argument_actually_reads_one():
    """An argument box on a program that ignores argv silently discards what the student typed."""
    bodies = _uprog_bodies()
    for prog in _prog_args():
        if prog not in bodies:          # stock xv6 program, not generated by GINI
            continue
        assert "argv[1]" in bodies[prog], f"{prog} offers an argument box but never reads argv[1]"


def test_every_program_that_reads_an_argument_is_offered_one():
    """The reverse gap: a parameter that exists in C but that no student can ever reach."""
    missing = [p for p, b in _uprog_bodies().items()
               if "argv[1]" in b and p not in _prog_args()]
    assert not missing, f"these read argv[1] but the launcher cannot pass it: {missing}"


def test_the_second_argument_is_advertised_wherever_it_exists():
    """Two programs take a second argument -- walker's per-page dwell and toucher's access order.
    Neither is discoverable except through the placeholder, so the placeholder has to show it."""
    bodies = _uprog_bodies()
    two = {p for p, b in bodies.items() if "argv[2]" in b}
    assert two == {"walker", "toucher"}, f"argv[2] users changed: {two}"
    args = _prog_args()
    assert "ticks" in args["walker"], "walker's dwell is invisible in the launcher"
    assert "rand" in args["toucher"], "toucher's access order is invisible in the launcher"


# -- the sanitiser holds --------------------------------------------------- #

@pytest.mark.parametrize("hostile", [
    "48; rm -rf /", "48 && reboot", "48 | sh", "`id`", "$(whoami)",
    "48\nkill 1", "../../etc/passwd", "48 > /dev/null", "48 'x'",
])
def test_no_shell_metacharacter_survives(hostile):
    """/run writes its command into a real shell, so this is the injection boundary."""
    out = _safe_args()(hostile)
    assert not any(c in out for c in ";&|`$()<>\n\\/'\""), f"{hostile!r} -> {out!r}"


def test_ordinary_arguments_pass_through_unharmed():
    f = _safe_args()
    assert f("48") == "48"
    assert f("48 rand") == "48 rand"
    assert f("  60  ") == "60"          # trimmed and collapsed
    assert f("") == ""


def test_a_long_argument_cannot_wedge_the_console():
    """The console is line-buffered; an unbounded string is a way to jam it."""
    assert len(_safe_args()("9" * 500)) <= 32


# -- the wiring ------------------------------------------------------------ #

def test_run_passes_args_through_to_the_agent():
    """The bridge must actually put args on the query string, url-encoded."""
    src = (ROOT / "frontend-ng" / "src" / "gini" / "runtime" / "xv6_bridge.py").read_text()
    body = src[src.index("def run(self, prog"):]
    body = body[:body.index("\n    def ")]
    assert "args" in body and "quote(" in body, "run() drops or fails to encode its arguments"


def test_launch_only_sends_args_for_programs_that_take_them():
    src = LAB.read_text()
    body = src[src.index("def _launch(self)"):]
    body = body[:body.index("\n    def ")]
    assert "_PROG_ARGS" in body, "_launch sends the box's text without checking the program takes it"


def test_a_refused_launch_says_why():
    """The bug that started this: /run returned a bare false and the UI showed nothing, so an
    image built before `walker` existed looked exactly like a launch that just didn't happen."""
    agent = AGENT.read_text()
    body = agent[agent.index('elif u.path == "/run"'):]
    body = body[:body.index('elif u.path == "/kill"')]
    assert "error" in body and "Rebuild" in body, "/run refuses without explaining itself"

    bridge = (ROOT / "frontend-ng" / "src" / "gini" / "runtime" / "xv6_bridge.py").read_text()
    run = bridge[bridge.index("def run(self, prog"):]
    run = run[:run.index("\n    def ")]
    assert "last_run_error" in run, "the bridge drops the agent's explanation"

    lab = LAB.read_text()
    assert "launch_failed" in lab, "the lab never surfaces a refused launch"


def test_the_agent_can_report_which_programs_it_knows():
    """The agent ships inside the image, so its list can lag the source. /programs makes that
    visible; without it a stale container is only diagnosable by reading the image."""
    assert '/programs' in AGENT.read_text(), "no way to ask a running agent what it accepts"
