#!/usr/bin/env python3
"""Build Stage 1 as ONE file, for machines where nothing is installed.

    python doctor/tools/bundle.py          # write doctor/src/gini_doctor/stage0/stage1-bundle.py
    python doctor/tools/bundle.py --check  # exit 1 if the committed bundle is stale (CI runs this)

`curl … | sh` and `irm … | iex` bring only Stage 0 onto a machine. When Stage 1 is neither next
to it (a checkout) nor installed, Stage 0 fetches this single file and runs it with the Python it
chose. The bundle carries every Stage 1 module and data file as text and imports them from memory
through a small meta-path finder, so it needs nothing but the standard library and writes nothing
to import itself.

The bundle is generated, committed, and checked for drift: a test asserts that building it from
the sources reproduces the committed file byte for byte.
"""
from __future__ import annotations

import sys
from pathlib import Path

DOCTOR = Path(__file__).resolve().parents[1]
SRC = DOCTOR / "src"
OUT = SRC / "gini_doctor" / "stage0" / "stage1-bundle.py"
MARKER = "# gini-doctor stage1 bundle"

RUNTIME = r'''
import importlib.abc
import importlib.util
import sys

_PREFIX = "<gini-doctor-bundle>"


class _Loader(importlib.abc.Loader):
    def __init__(self, rel):
        self.rel = rel

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        exec(compile(FILES[self.rel], _PREFIX + "/" + self.rel, "exec"), module.__dict__)

    def get_data(self, path):
        rel = str(path).replace("\\", "/").split(_PREFIX + "/", 1)[-1]
        if rel not in FILES:
            raise OSError("not in the gini-doctor bundle: %s" % rel)
        return FILES[rel].encode("utf-8")


class _Finder(importlib.abc.MetaPathFinder):
    def find_spec(self, name, path=None, target=None):
        rel = name.replace(".", "/")
        for candidate, is_pkg in ((rel + "/__init__.py", True), (rel + ".py", False)):
            if candidate in FILES:
                spec = importlib.util.spec_from_loader(name, _Loader(candidate), is_package=is_pkg,
                                                       origin=_PREFIX + "/" + candidate)
                spec.has_location = True
                if is_pkg:
                    spec.submodule_search_locations = [_PREFIX + "/" + rel]
                return spec
        return None


def _main():
    sys.meta_path.insert(0, _Finder())
    from gini_doctor.stage1.cli import main
    return main()


if __name__ == "__main__":
    sys.exit(_main())
'''


def sources():
    """Every file the bundle carries, as (relative path, text), in a stable order."""
    root = SRC / "gini_doctor" / "stage1"
    files = [("gini_doctor/__init__.py", '"""gini-doctor, bundled: only Stage 1 is inside."""\n')]
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix in (".py", ".json") and "__pycache__" not in path.parts:
            rel = path.relative_to(SRC).as_posix()
            files.append((rel, path.read_text(encoding="utf-8")))
    return files


def build() -> str:
    out = ["#!/usr/bin/env python3",
           MARKER,
           "# GENERATED by doctor/tools/bundle.py from doctor/src/gini_doctor/stage1 — do not edit.",
           "# Run it with any Python 3.8+:  python3 stage1-bundle.py run --only system",
           "FILES = {"]
    for rel, text in sources():
        out.append("    %r: %r," % (rel, text))
    out.append("}")
    return "\n".join(out) + "\n" + RUNTIME


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    text = build()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("stage1-bundle.py is stale: run python doctor/tools/bundle.py", file=sys.stderr)
            return 1
        print("stage1-bundle.py matches the sources")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s (%d bytes)" % (OUT, len(text.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
