"""Entry point: launch the REAL gRouter wired into the portable fabric.

Reads ROUTER_CONFIG (the same per-router wiring our frontend compiler already emits)
and turns it into the gRouter's NATIVE config — `ifconfig add tun…` + `route add…`,
using the legacy `tun` interface, which is a userspace UDP socket. This is the seam
where the new portable fabric meets the real C router.

ROUTER_CONFIG = {
  "name": "r1",
  "ifaces": [
    {"ip": "10.0.1.1/24", "mac": "02:..:01", "port": {"peer_host": "m1", "peer_port": 5000}},
    ...
  ]
}
"""
from __future__ import annotations

import ipaddress
import os
import socket
import subprocess
import sys
import time

GROUTER = os.environ.get("GROUTER_BIN", "/usr/local/bin/grouter")


def resolve(host: str) -> str:
    for _ in range(20):                      # Docker DNS can lag at startup
        try:
            return socket.gethostbyname(host)
        except OSError:
            time.sleep(0.5)
    return host


def build_config(cfg: dict) -> str:
    # OpenFlow (OVS) mode: the gRouter is an L2 switch programmed by a controller, so
    # the tun ports come up (with link-local placeholder addresses) but get NO routes —
    # frames are switched by the flow table, not routed.
    openflow = bool(cfg.get("openflow"))
    lines = ["# generated by run_grouter.py — gRouter native config"]
    routes = []
    for i, itf in enumerate(cfg["ifaces"], start=1):     # tun0 is reserved for tap
        dev = f"tun{i}"
        iface = ipaddress.ip_interface(itf["ip"])
        ip = str(iface.ip)
        peer = itf["port"]
        peer_ip = resolve(peer["peer_host"])
        # Literal-port wiring: the router binds its local UDP port (bind_port) and
        # the peer (the machine's shuttle) sends FROM peer_port. -srcport makes the
        # tun driver use these literal ports instead of the legacy BASEPORTNUM/name
        # formula, so the portable fabric interoperates with the real C router.
        srcport = peer.get("bind_port")
        # -srcport is optional and parsed in the trailing-args region, so it must
        # come AFTER -addr/-hwaddr (the fixed parser expects -addr after -dstport).
        srcport_opt = f" -srcport {srcport}" if srcport is not None else ""
        lines.append(
            f"ifconfig add {dev} -dstip {peer_ip} -dstport {peer['peer_port']} "
            f"-addr {ip} -hwaddr {itf['mac']} -mtu 1400{srcport_opt}"
        )
        if not openflow:
            routes.append(
                f"route add -dev {dev} -net {iface.network.network_address} "
                f"-netmask {iface.network.netmask}"
            )
    # static inter-router routes (the compiler computes next-hops; no routing protocol)
    for rt in cfg.get("routes", []):
        routes.append(
            f"route add -dev tun{rt['dev']} -net {rt['net']} "
            f"-netmask {rt['mask']} -gw {rt['gw']}"
        )
    lines += routes
    return "\n".join(lines) + "\n"


def grouter_cmd(conf: str, confdir: str, name: str, openflow_port: int | None = None) -> list[str]:
    """The exact argv used to launch the gRouter. Kept as a function so a test can
    assert the option spelling (the binary only accepts --config / --confpath / -p).
    In OVS mode we add --openflow=<port>, which flips the gRouter into an OpenFlow 1.0
    switch that connects to the controller named by GINI_OF_CONTROLLER."""
    argv = [GROUTER, "--config=" + conf, "--confpath=" + confdir]
    if openflow_port is not None:
        argv.append(f"--openflow={openflow_port}")
    argv.append(name)
    return argv


def clear_stale_pidfile(confdir: str, name: str) -> None:
    """Remove <confdir>/<name>.pid before starting.

    The gRouter refuses to start when that file names a live process — sound on a workstation,
    WRONG inside a container. A restarted container begins its PID namespace at 1 again, so the
    number in a leftover pid file is near-certain to belong to some new process (ttyd, this
    script, the router itself), `kill(pid, 0)` succeeds, and the router aborts:

        r1: fatal: [makePIDFile]:: Another router is still running under: /run/r1.pid
        [r1] gRouter exited (1); stopping container.

    which then loops: the container restarts, finds the same file, and dies again. One crash
    became a router that could never come back.

    Deleting it here is safe precisely because of where "here" is: this script IS the container's
    entrypoint, so reaching this line means the container has just started and no previous router
    of ours survived. The C-side liveness check stays as it is — it is still right for someone
    running two routers on one host outside a container.
    """
    path = os.path.join(confdir, f"{name}.pid")
    try:
        with open(path) as f:
            stale = f.read().strip()
    except OSError:
        return                                     # no pid file: the ordinary case
    try:
        os.remove(path)
        print(f"[{name}] removed stale pid file {path} (held pid {stale}); the container "
              f"restarted, so that pid belongs to something else now.", file=sys.stderr)
    except OSError as e:
        print(f"[{name}] WARNING: could not remove {path}: {e}", file=sys.stderr)


def main() -> int:
    raw = os.environ.get("ROUTER_CONFIG")
    if not raw:
        print("ROUTER_CONFIG not set", file=sys.stderr)
        return 2
    import json
    cfg = json.loads(raw)
    name = cfg.get("name", "r1")

    confdir = "/run"
    conf = os.path.join(confdir, f"{name}.conf")
    with open(conf, "w") as f:
        f.write(build_config(cfg))
    print(f"[{name}] config:\n{open(conf).read()}", file=sys.stderr)

    clear_stale_pidfile(confdir, name)

    # launch the real gRouter, sourcing the generated config (OVS mode -> --openflow)
    of = cfg.get("openflow")
    of_port = of.get("port") if isinstance(of, dict) else (6633 if of else None)
    cmd = grouter_cmd(conf, confdir, name, openflow_port=of_port)
    print(f"[{name}] exec: {' '.join(cmd)}", file=sys.stderr)
    proc = subprocess.Popen(cmd, stdin=subprocess.DEVNULL)
    rc = proc.wait()
    # Do NOT silently hold a dead router "running" — that masks failures and shows a
    # green node in the GUI while nothing forwards. Propagate the exit so the container
    # stops and the node turns red. Set GINI_HOLD_ON_EXIT=1 to keep it up for debugging.
    if os.environ.get("GINI_HOLD_ON_EXIT") == "1":
        print(f"[{name}] gRouter exited ({rc}); holding container (GINI_HOLD_ON_EXIT).",
              file=sys.stderr)
        while True:
            time.sleep(3600)
    print(f"[{name}] gRouter exited ({rc}); stopping container.", file=sys.stderr)
    return rc if rc is not None else 1


if __name__ == "__main__":
    raise SystemExit(main())
